# Generated by Django 5.2.1 on 2025-05-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_age_profile_height_cm_profile_sex_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
