# Generated by Django 5.2.1 on 2025-05-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
