# Generated by Django 5.2.1 on 2025-05-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
