# Generated by Django 5.2.1 on 2025-05-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('difficulty', models.CharField(max_length=50)),
                ('tutorial', models.TextField()),
                ('image', models.ImageField(default='exercises/default.jpg', upload_to='exercises/')),
            ],
        ),
    ]
