# Generated by Django 5.2.1 on 2025-05-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_rename_tutorial_exercise_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='exercise',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='exercise_name',
            field=models.CharField(default='Rest Day', max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
    ]
