# Generated by Django 5.2.1 on 2025-05-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='weight',
            new_name='height_cm',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='height',
            new_name='weight_kg',
        ),
    ]
