# Generated by Django 5.2.1 on 2025-05-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_profile_age_alter_profile_sex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
