# Generated by Django 5.2.1 on 2025-05-24 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_remove_notification_time_notification_time_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
