# Generated by Django 5.2.1 on 2025-05-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_workoutsession_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='date',
        ),
    ]
