# Generated by Django 5.2.1 on 2025-05-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_remove_workoutsession_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
    ]
