# Generated by Django 5.2.1 on 2025-05-29 05:39

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_alter_workoutsession_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=27),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_hour',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
