# Generated by Django 5.2.1 on 2025-05-29 06:50

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_notification_enabled_alter_notification_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='notification',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=27),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_hour',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_minute',
            field=models.IntegerField(default=0),
        ),
    ]
